/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFoundryRouteImport } from './routes/_authenticated/foundry'
import { Route as AuthenticatedAzureRouteImport } from './routes/_authenticated/azure'
import { Route as ApiPublicFoundryMcpRouteImport } from './routes/api/public/foundry-mcp'
import { Route as ApiPublicDaftraMcpRouteImport } from './routes/api/public/daftra-mcp'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoundryRoute = AuthenticatedFoundryRouteImport.update({
  id: '/foundry',
  path: '/foundry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAzureRoute = AuthenticatedAzureRouteImport.update({
  id: '/azure',
  path: '/azure',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFoundryMcpRoute = ApiPublicFoundryMcpRouteImport.update({
  id: '/api/public/foundry-mcp',
  path: '/api/public/foundry-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDaftraMcpRoute = ApiPublicDaftraMcpRouteImport.update({
  id: '/api/public/daftra-mcp',
  path: '/api/public/daftra-mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/azure': typeof AuthenticatedAzureRoute
  '/foundry': typeof AuthenticatedFoundryRoute
  '/api/public/daftra-mcp': typeof ApiPublicDaftraMcpRoute
  '/api/public/foundry-mcp': typeof ApiPublicFoundryMcpRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/azure': typeof AuthenticatedAzureRoute
  '/foundry': typeof AuthenticatedFoundryRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/daftra-mcp': typeof ApiPublicDaftraMcpRoute
  '/api/public/foundry-mcp': typeof ApiPublicFoundryMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/azure': typeof AuthenticatedAzureRoute
  '/_authenticated/foundry': typeof AuthenticatedFoundryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/daftra-mcp': typeof ApiPublicDaftraMcpRoute
  '/api/public/foundry-mcp': typeof ApiPublicFoundryMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/azure'
    | '/foundry'
    | '/api/public/daftra-mcp'
    | '/api/public/foundry-mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/azure'
    | '/foundry'
    | '/'
    | '/api/public/daftra-mcp'
    | '/api/public/foundry-mcp'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/azure'
    | '/_authenticated/foundry'
    | '/_authenticated/'
    | '/api/public/daftra-mcp'
    | '/api/public/foundry-mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDaftraMcpRoute: typeof ApiPublicDaftraMcpRoute
  ApiPublicFoundryMcpRoute: typeof ApiPublicFoundryMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foundry': {
      id: '/_authenticated/foundry'
      path: '/foundry'
      fullPath: '/foundry'
      preLoaderRoute: typeof AuthenticatedFoundryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/azure': {
      id: '/_authenticated/azure'
      path: '/azure'
      fullPath: '/azure'
      preLoaderRoute: typeof AuthenticatedAzureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/foundry-mcp': {
      id: '/api/public/foundry-mcp'
      path: '/api/public/foundry-mcp'
      fullPath: '/api/public/foundry-mcp'
      preLoaderRoute: typeof ApiPublicFoundryMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daftra-mcp': {
      id: '/api/public/daftra-mcp'
      path: '/api/public/daftra-mcp'
      fullPath: '/api/public/daftra-mcp'
      preLoaderRoute: typeof ApiPublicDaftraMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAzureRoute: typeof AuthenticatedAzureRoute
  AuthenticatedFoundryRoute: typeof AuthenticatedFoundryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAzureRoute: AuthenticatedAzureRoute,
  AuthenticatedFoundryRoute: AuthenticatedFoundryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDaftraMcpRoute: ApiPublicDaftraMcpRoute,
  ApiPublicFoundryMcpRoute: ApiPublicFoundryMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
