// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqltlqbwhkiibgjiirje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbHRscWJ3aGtpaWJnamlpcmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3Nzc5MzksImV4cCI6MjA5NjM1MzkzOX0.BaMp5dYWwWgbYw19llYBdiEYz_A2OOwRkd_HhVx4BwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});